runtime: nodejs18

env: 
  NODE_ENV: 'production'
  GCLOUD_STORAGE_BUCKET: ${GCLOUD_STORAGE_BUCKET}
  
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 5

entrypoint: npm start
