runtime: nodejs18 # Utiliza la versión de Node.js que prefieras que sea compatible
env: standard
instance_class: F1 # Clase de instancia, F1 es la más económica
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
handlers:
- url: /.*
  static_files: public/\1
  upload: public/(.*)
- url: /(.*\.(json|ico|js|css))
  static_files: static/\1
  upload: static/(.*\.(json|ico|js|css))
